### ISSUE TITLE
Tipse andre om prosjektet

### ISSUE THREAD

**Issue by livarb** [jnystad/datanorge#6]
Hei!

Tenkte det var enklast å legge inn eit issue her :)

Post gjerne om prosjektet i Datalandsbyen, så fleire kan finne det:
https://datalandsbyen.norge.no/category/2/gode-eksempler-p%C3%A5-bruk

Trur det er fleire som er interesserte. Laga liknande, men mykje enklare, løysing for eit par år sidan og det var fleire som var interesserte.

**Comment by jnystad** [comment]
Hei!

Takk for tipset!

I forbindelse med en oppfrisking av dette prosjektet har jeg nå (omsider) lagt inn et innlegg som nevner både dette og et tilsvarende prosjekt for geonorge.no (geono).
